const ErrorCodes = {
  // Umumy
  SERVER_ERROR: "SERVER_ERROR",
  MISSING_DETAILS: "MISSING_DETAILS",
  DATA_MISSING: "DATA_MISSING",
  UNAUTHORIZED_ACTION: "UNAUTHORIZED_ACTION",

  // Auth / User
  INVALID_EMAIL: "INVALID_EMAIL",
  WEAK_PASSWORD: "WEAK_PASSWORD",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  PROFILE_UPDATED: "PROFILE_UPDATED",

  // Appointment
  DOCTOR_NOT_AVAILABLE: "DOCTOR_NOT_AVAILABLE",
  SLOT_NOT_AVAILABLE: "SLOT_NOT_AVAILABLE",
  APPOINTMENT_BOOKED: "APPOINTMENT_BOOKED",
  APPOINTMENT_CANCELLED: "APPOINTMENT_CANCELLED",
  APPOINTMENT_CANCELLED_OR_NOT_FOUND: "APPOINTMENT_CANCELLED_OR_NOT_FOUND",
  APPOINTMENT_COMPLETED: "APPOINTMENT_COMPLETED",
  MARK_FAILED: "MARK_FAILED",
  CANCELLATION_FAILED: "CANCELLATION_FAILED",

  // Payment
  PAYMENT_SUCCESSFUL: "PAYMENT_SUCCESSFUL",
  PAYMENT_FAILED: "PAYMENT_FAILED",

  // Doctor
  AVAILABILITY_CHANGED: "AVAILABILITY_CHANGED",
  DOCTOR_ADDED: "DOCTOR_ADDED",
};

export default ErrorCodes;